#
server:
  port: 8089
spring:
  datasource: #?????
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gj200903
    url: jdbc:mysql://localhost:3306/covid?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true





#mybatis:
#  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      example:
        mapper:
          debug
